use crate::driver::DriverError;

/// Maps a `zbus`/D-Bus failure onto the backend-agnostic `DriverError`,
/// using BlueZ's well-known D-Bus error names where they tell us more than
/// "backend failed".
pub(crate) fn map_zbus_error(err: zbus::Error) -> DriverError {
    if let zbus::Error::MethodError(name, detail, _) = &err {
        return match name.as_str() {
            "org.bluez.Error.NotReady" => DriverError::NotReady,
            "org.bluez.Error.DoesNotExist"
            | "org.freedesktop.DBus.Error.UnknownObject"
            | "org.freedesktop.DBus.Error.UnknownInterface"
            | "org.freedesktop.DBus.Error.UnknownMethod" => DriverError::NotFound,
            "org.bluez.Error.NotAuthorized" | "org.bluez.Error.AuthenticationFailed" => {
                DriverError::PermissionDenied
            }
            "org.bluez.Error.NotSupported" => {
                DriverError::Unsupported("not supported by this adapter/device")
            }
            "org.freedesktop.DBus.Error.NoReply" | "org.freedesktop.DBus.Error.Timeout" => {
                DriverError::Timeout
            }
            other => DriverError::Backend(detail.clone().unwrap_or_else(|| other.to_string())),
        };
    }
    // `Connection::builder().method_timeout(...)` expiring surfaces as a
    // plain io::Error(TimedOut) wrapped in InputOutput, not a MethodError
    // - it never got a reply to inspect, D-Bus or otherwise.
    if let zbus::Error::InputOutput(io_err) = &err
        && io_err.kind() == std::io::ErrorKind::TimedOut
    {
        return DriverError::Timeout;
    }
    DriverError::Backend(err.to_string())
}

/// `Properties.GetAll`/`ObjectManager.GetManagedObjects` are generated by
/// `zbus`'s own `#[interface]` macro and so return `zbus::fdo::Error`
/// rather than `zbus::Error`; unwrap it and map the same way.
pub(crate) fn map_fdo_error(err: zbus::fdo::Error) -> DriverError {
    match err {
        zbus::fdo::Error::ZBus(inner) => map_zbus_error(inner),
        other => DriverError::Backend(other.to_string()),
    }
}
